# Generated by Django 5.2.11 on 2026-03-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_created_at_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('politics', 'Politics'), ('education', 'Education'), ('business', 'Business')], default='technology', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
